# Chapter 1 - Vector, Matrix & Array

**_CHENG-WEI, HSUEH_**

## 1-1 Declear a array

In [15]:
#First import the library, numpy - a tool used to cope with array.   

import numpy as np

#Declear a raw dimension array with numpy
R1_arr = np.array([1,2,3,4,5,6,7])

#Declear a two-dimension array with numpy
D2_arr = np.array([[1,4],[2,5],[3,6]])

#Declear a column array with numpy
C1_arr = np.array([[1],[2],[3]])

#Now print them out
print(R1_arr)
print(D2_arr)
print(C1_arr)

[1 2 3 4 5 6 7]
[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]]


## 1-2 Declear a matrix

In [5]:
#First import the library, numpy - a tool used to cope with matrix.   

import numpy as np

#Declear a raw dimension matrix with numpy
R1_mat = np.mat([1,2,3])

#Declear a two-dimension matrix with numpy
D2_mat = np.mat([[1,4],[2,5],[3,6]])

#Declear a column matrix with numpy
C1_mat = np.mat([[1],[2],[3]])

#Now print them out
print(R1_mat)
print(D2_mat)
print(C1_mat)

[[1 2 3]]
[[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]]


**Review**

1. Although matrixs resemble arrays, in fact, the standard data structure of numpy is arrays; thus, most returning variables are arrays.
2. Based on the official document, matrixs is planned to be removed in the future, replaced by arrays.

## Chapter 1-3 Declear a sparse matrix(array)
**An array with sparse non-zero variable**

In [41]:
#Import library
import numpy as np
from scipy import sparse

#Declear an array
arr = np.array([[0,0],
                [0,1],
                [3,0]])

#Produce a compressed spare array
arr_sparse = sparse.csr_matrix(arr)

'''
In some situations, when anaylzed, the data with massive zero-variable can turn into sparse arrays so as to reduce wasted memory and time.

Now let's look the array after compression
'''

print(arr_sparse)

  (1, 1)	1
  (2, 0)	3


In [43]:
#Another bigger sparse matrix
arr_2 = np.array([[0 ,0 ,0 ,1 ,0 ,0],
                [0 ,2 ,0 ,0 ,0 ,0],
                [0 ,9 ,0 ,0 ,4 ,0],
                [0 ,0 ,0 ,0 ,0 ,0],
                [0 ,3 ,0 ,0 ,0 ,0],
                [0 ,0 ,0 ,0 ,5 ,0]])
arr_sparse2 = sparse.csr_matrix(arr_2)
print(arr_sparse2)

  (0, 3)	1
  (1, 1)	2
  (2, 1)	9
  (2, 4)	4
  (4, 1)	3
  (5, 4)	5


## 1-4 & 1-5 Select the elemts & the deailed information of arrays

In [49]:
#Take above arrays as an example

#Select the third element in one row array
print(R1_arr[2])

#Select the elements from third to sixth in one row array
print(R1_arr[2:5])

#Select the all of the elements in one row array
print(R1_arr[:])

#Select an element in a 2-dimension array
print(arr[1,0])

#Select the elements in a 2-dimension array
print(arr_2[2:,3:-1])


'''
A way to reverse array
'''
print(R1_arr[::-1])

'''
Chapter 1-5 The detailed information of arrays
'''

#Get the shape of arrays
print(R1_arr.shape)

#Size represents the total number of elements
print(R1_arr.size)

#the number of dimension
print(R1_arr.ndim)

3
[3 4 5]
[1 2 3 4 5 6 7]
0
[[0 4]
 [0 0]
 [0 0]
 [0 5]]
[7 6 5 4 3 2 1]
(7,)
7
1
